### ISSUE TITLE
Api is not working

### ISSUE THREAD

**Issue by haridroid** [IsaiasCuvula/recipe_mvvm_android_app#1]
plz update sample json object 
https://designer.mocky.io/design/confirmation

**Comment by IsaiasCuvula** [comment]
Not working, whats kind of response are you getting?

**Comment by haridroid** [comment]
Api : http://www.recipepuppy.com/api/ 404 File Not Found

**Comment by haridroid** [comment]
Sample JSON object
{
  "title": "Recipe Puppy",
  "version": 0.1,
  "href": "http:\/\/www.recipepuppy.com\/",
  "results": [
        {
            "title": "Roasted Garlic Grilling Sauce \r\n\t\t\r\n\t\r\n\t\t\r\n\t\r\n\t\t\r\n\t\r\n\t\r\n\r\n",
            "href": "http:\/\/www.kraftfoods.com\/kf\/recipes\/roasted-garlic-grilling-sauce-56344.aspx",
            "ingredients": "garlic, onions, hot sauce",
            "thumbnail": "http:\/\/img.recipepuppy.com\/634118.jpg"
        }
   ]
}

**Comment by IsaiasCuvula** [comment]
I double-check right now, and I realize that the API is not working anymore, try to use another one, please
